config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :events
  devise_for :users
  resources :rooms
  resources :landlords
  resources :properties
  get 'welcome/index'

  root 'welcome#index'
end

app/models/property.rb
class Property < ApplicationRecord
  has_many :rooms
  has_many :viewings
  has_many :events, through: :viewings
  has_one :landlord
  has_one_attached :property_image

  serialize :property_type, Array

  def property_name
    "#{number} #{street}"
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  # after_create :create_associated_rooms, on: :create
  helper_method :create_associated_rooms

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def create_associated_rooms
    property = Property.find(params[:id])
    # @rooms_to_create = Property.find(params[:id])
    # Room.new(params.permit(id: property.id))
    # "ROOMS: #{num_rooms}"


    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end

  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:number, :street, :address_line_2, :city, :county, :postcode, :property_image, :number_of_rooms, property_type:[])
    end

end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= simple_form_for @property do |f| %>

  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :number %>
    <%= f.text_field :number, id: :property_number, class: 'form-control' %>
  </div>

  <%= f.file_field :property_image %>

  <div class="form-group">
    <%= f.label :street %>
    <%= f.text_field :street, id: :property_street, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address_line_2 %>
    <%= f.text_field :address_line_2, id: :property_address_line_2, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, id: :city, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :county %>
    <%= f.text_field :county, id: :property_county, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :postcode %>
    <%= f.text_field :postcode, id: :property_postcode, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.input :property_type, as: :check_boxes, collection: %w(Student Graduate Professional Family) %>
  </div>

  <div class="form-group">
    <%= f.label :number_of_rooms %>
    <%= f.text_field :number_of_rooms, id: :number_of_rooms, class: 'form-control' %>  </div>

  <div class="actions">
    <%= f.submit 'Update', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'View property', @property, class: 'btn btn-primary' %> |
<%= link_to 'Cancel', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('.title') %></h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Number</th>
      <th>Street</th>
      <th>Address line 2</th>
      <th>City</th>
      <th>Postcode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.number %></td>
        <td><%= property.street %></td>
        <td><%= property.address_line_2 %></td>
        <td><%= property.city %></td>
        <td><%= property.postcode %></td>
        <td><%= link_to (fa_icon 'search'), property %></td>
        <td><%= link_to (fa_icon 'edit'), edit_property_path(property) %></td>
        <td><%= link_to (fa_icon 'trash'), property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_property_path, class: 'btn btn-primary' %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <h2><%= @property.property_name %></h2>
  <div class="row">
    <div class="col">
      <h3>Images</h3>
      <%= image_tag(@property.property_image, class: 'img-fluid') if @property.property_image.attached? %>
    </div>
    <div class="col">
      <h3>Details</h3>
      <p>
        <strong>Number of rooms:</strong>
        <%= @property.number_of_rooms %>
      </p>
      <%#= link_to 'Create rooms', controller: :rooms, action: :new %>
      <%#= link_to 'Create rooms', create_associated_rooms %>
      <p>
        <strong>Address line 2:</strong>
        <%= @property.address_line_2 %>
      </p>

      <p>
        <strong>City:</strong>
        <%= @property.city %>
      </p>

      <p>
        <strong>County:</strong>
        <%= @property.county %>
      </p>

      <p>
        <strong>Postcode:</strong>
        <%= @property.postcode %>
      </p>
    </div>
  </div>
</div>


<%= link_to 'Edit', edit_property_path(@property), class: 'btn btn-primary' %> |
<%= link_to 'Back', properties_path, class: 'btn btn-secondary' %>