config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :events
  devise_for :users
  resources :rooms
  resources :landlords
  resources :properties
  get 'welcome/index'

  root 'welcome#index'
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :viewings
  has_many :properties, through: :viewings
  belongs_to :user


  # validate :expiration_date_cannot_be_in_the_past
  validates :title, presence: true
  # validate :end_time_after_start_time?
  attr_accessor :date_range


  # def end_time_after_start_time?
  #   if :end < :start
  #     errors.add :end, "must be after start time"
  #   end
  # end

  def expiration_date_cannot_be_in_the_past
    if expiration_date.present? && expiration_date < Date.today
      errors.add(:end, "can't be in the past")
    end
  end

  def event_name
    if event_type == 1
      event_name = 'Viewing'
    elsif event_type == 2
      event_name = 'Maintainence'
    elsif event_type == 3
      event_name = 'Landlord check'
    elsif event_type == 4
      event_name = 'Staff Holiday'
    end
  end

  # def all_day_event?
  #   self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :verify_authenticity_token, :only => :create

  # GET /events
  # GET /events.json
  def index
    @events = Event.where(start: params[:start]..params[:end])
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    @event.save
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event.update(event_params)

  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :start, :end, :event_type, :notes, :property_id, :user_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit.html.erb
<div class="modal fade" id="edit_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Edit Event</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>
<!--<div class="container">-->
<!--  <div class="row">-->
<!--    <div class="col-12">-->
<!--      <h1>Create a new event</h1>-->
<!--    </div>-->

    <%#= render 'form', event: @event %>
<!--  </div>-->

<!--</div>-->

app/views/events/_form.html.erb
<%= simple_form_for @event, remote: true do |f| %>
  <div class="row">
    <div class="col-12">
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
    </div>

    <div class="col">
      <div class="form-inputs">
        <%= f.input :title %>
        <div class="form-group">
          <%= f.label :property_id %>
          <%= f.collection_select(:property_id, Property.all, :id, :property_name, {}, {class: 'form-control'}) %>
        </div>

        <div class="form-group">
          <%= f.label :user_id, 'Agent' %>
          <%= f.collection_select(:user_id, User.all, :id, :username, {}, {class: 'form-control'}) %>
        </div>

        <div class="form-group">
          <%= f.label :event_type %>
          <%= f.select(:event_type, options_for_select([ ['Viewing', 1], ['Maintainence', 2] ] ), {}, {:class => 'form-control'})  %>
        </div>

        <%= f.input :start, as: :time, start_year: Date.current.year, end_year: Date.today.year + 1 %>
        <%= f.input :end, as: :time %>
      </div>
      <div class="form-group">
        <%= f.input :notes %>
      </div>
    </div>

    <div class="col-12">
      <div class="form-actions text-right">
        <%= f.button :submit, class: 'btn btn-primary' %>
        <%= link_to 'Cancel', events_path, class: 'btn btn-secondary' %>
        <%= link_to 'Delete',
                    event,
                    method: :delete,
                    class: 'btn btn-danger',
                    data: { confirm: 'Are you sure?' },
                    remote: true unless @event.new_record? %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_new.html.erb
<div class="modal fade" id="new_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">New Event</h4>
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>
<!--<div class="container">-->
<!--  <div class="row">-->
<!--    <div class="col-12">-->
<!--      <h1>Create a new event</h1>-->
<!--    </div>-->

    <%#= render 'form', event: @event %>
<!--  </div>-->

<!--</div>-->

app/views/events/create.js.erb
$('.calendar').fullCalendar(
    'renderEvent',
    $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
    true
);
$('.modal').modal('hide');

app/views/events/destroy.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>])
$('.modal').modal('hide');

app/views/events/edit.html.erb
<%= render 'form', event: @event %>

app/views/events/edit.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_event').modal('show');

app/views/events/index.html.erb
<h1>Events</h1>

<div class="calendar"></div>
<br>

<%= link_to 'New Event', new_event_path, class: 'btn btn-primary' %>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Create a new event</h1>
    </div>

    <%= render 'form', event: @event %>
  </div>

</div>

app/views/events/new.js.erb
$('#remote_container').html('<%= j render "new" %>');
$('#new_event').modal('show');

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Event Type:</strong>
  <%= @event.event_type %>
</p>



<p>
  <strong>Note:</strong>
  <%= @event.notes %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @event.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @event.end_time %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/events/update.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>]);
$('.calendar').fullCalendar(
    'renderEvent',
    $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
    true
);
$('.modal').modal('hide');