config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :events
  devise_for :users
  resources :rooms
  resources :landlords
  resources :properties
  get 'welcome/index'

  root 'welcome#index'
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :property
  belongs_to :landlord

  def room_details
    "#{number} #{title} #{price}"
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: I18n.t('room.create') }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:number, :title, :description, :tenancy_start, :tenancy_end, :price, :property_id, :landlord_id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for(@room, html: { class: '' }) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :number %>
    <%= form.text_field :number, id: :room_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :room_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :room_description, class: 'form-control' %>
  </div>

  <div class="form-row align-items-center">
    <%= form.label :tenancy_start, class: 'my-1 mr-2' %>
    <%= form.date_select :tenancy_start, {id: :room_tenancy_start}, {class: 'form-control col-sm-2 my-1'} %>
  </div>

  <div class="form-row align-items-center">
    <%= form.label :tenancy_end, class: 'my-1 mr-2' %>
    <%= form.date_select :tenancy_end, {id: :room_tenancy_end}, {class: 'form-control col-sm-2 my-1'} %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, id: :room_price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :property_id %>
    <%= form.collection_select(:property_id, Property.all, :id, :property_name, {}, {class: 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= form.label :landlord_id %>
    <%= form.collection_select(:landlord_id, Landlord.all, :id, :landlord_name, {}, {class: 'form-control'}) %>
  </div>

  <div class="actions">
    <%= form.submit 'Update', class: 'btn btn-primary' %>
    <%= link_to 'Back', rooms_path, class: 'btn btn-secondary' %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'View room', @room, class: 'btn btn-primary' %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Property</th>
      <th>Room No.</th>
      <th>Title</th>
      <th>Tenancy start</th>
      <th>Tenancy end</th>
      <th>Price</th>
      <th>Landlord</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.property.property_name %></td>
        <td><%= room.number %></td>
        <td><%= room.title %></td>
        <td><%= room.tenancy_start.to_formatted_s(:rfc822) %></td>
        <td><%= room.tenancy_end.to_formatted_s(:rfc822) %></td>
        <td>&#163;<%= room.price %></td>
        <td><%= room.landlord.landlord_name %></td>
        <td><%= link_to (fa_icon 'search'), room %></td>
        <td><%= link_to (fa_icon 'edit'), edit_room_path(room) %></td>
        <td><%= link_to (fa_icon 'trash'), room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path, class: 'btn btn-primary' %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col">
    <p>
      <strong>Property:</strong>
      <%= @room.property.property_name %>
      <%= @room.property.county %>
    </p>
    <%= image_tag(@room.property.property_image, class: 'img-fluid') if @room.property.property_image.attached?  %>
  </div>

  <div class="col">
    <p>
      <strong>Room Number:</strong>
      <%= @room.number %>
    </p>

    <p>
      <strong>Title:</strong>
      <%= @room.title %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @room.description %>
    </p>

    <p>
      <strong>Tenancy start:</strong>
      <%= @room.tenancy_start %>
    </p>

    <p>
      <strong>Tenancy end:</strong>
      <%= @room.tenancy_end %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @room.price %>
    </p>

    <p>
      <strong>Landlord:</strong>
      <%= @room.landlord.landlord_name %>
    </p>
  </div>
</div>




<%= link_to 'Edit', edit_room_path(@room), class: 'btn btn-primary' %> |
<%= link_to 'Back', rooms_path, class: 'btn btn-secondary' %>