config/routes.rb
Rails.application.routes.draw do
  resources :tenants
  resources :events
  devise_for :users
  resources :rooms
  resources :landlords
  resources :properties
  get 'welcome/index'

  root 'welcome#index'
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
      <%= link_to image_tag('logo.svg', class: 'img-fluid'), root_path, class: 'home-link' %>
      <% if user_signed_in? %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item <%= 'active' if current_page?(properties_path) %>">
              <%= link_to 'Properties', properties_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= 'active' if current_page?(rooms_path) %>">
              <%= link_to 'Rooms', rooms_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= 'active' if current_page?(landlords_path) %>">
              <%= link_to 'Landlords', landlords_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= 'active' if current_page?(events_path) %>">
              <%= link_to 'Events', events_path, class: 'nav-link' %>
            </li>
            <li class="nav-item <%= 'active' if current_page?(tenants_path) %>">
              <%= link_to 'Tenants', tenants_path, class: 'nav-link' %>
            </li>
          </ul>
        </div>
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
            Logged in as <strong id="nav-username"><%= current_user.username %></strong>.
            <%= link_to fa_icon('user'), edit_user_registration_path, :class => 'edit-user navbar-link' %> |
            <%= link_to fa_icon('sign-out-alt'), destroy_user_session_path, method: :delete, class: 'navbar-link logout'  %>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to 'Login', new_user_session_path, class: 'navbar-link login'  %>
          <% end %>
        </p>
      <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityLets</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon-32x32.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <%= render partial: "layouts/nav" %>

  <div class="container">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    <div id="remote_container"></div>
  </div>
  </body>
</html>